language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "VeCU787P+nYo14/nXgAQSB6q7il3XAopkY+LW5xOUKjrgy/5p9wiOTuXClMrgWSQyyHTWrh723avFxhPVZttAt8wVZ5TdWCe3MEnmMXgRW27UeOITrfP9FbDXDvk2fBAEoyJ2kO3ak6TJRy4iIHmEW6b3wVS9G2pwEOOOqMTxKuR9VCY9SMPdSk7iCZXcL57Z6AzHD891LfNv1WvtuCrQv8j5LfBkY14wtzvsgj0hV3Snm9tE998+SGHg/vpfsRM1jca6k9+TTNZRIaAcBgdwgR1jlqoxhxBVyko/p6DiNofZM85cn0ikunOr22EZsiQUuSVQbk4Wg+/aUxW7sVrtpn7LKzewh+R8lizt1ao0pJdFZ5EI65Fc0e/Iy1H/ZbZCqJ5VnDKZFHuRqBf0bryEmoV90gyNn0pzijLr+7UaHfD4krf68wbI8WjP6S3dOBtFKFLVRsnQ33vUM2tXtahF+rVH6FmyzFdNNEiu8aFdgfSAA/8CmbTc54fdxkT+0r7QX3RuGw1kAwoi2WomRihJ7reIRkPZvjjru78CMDhlOaGnWIuLyFMWXtG0FyWsAiTZj5XJXPYgzPPxwSzfsO3Rcu8rdTrqRGozJktAMDa1MFU5qKcaFUQcEVhk6rOHjL8GwPdFC7YI7J7QcbSAB1PypBigsHJwZbV2m4eQ0uJ1WI="
    file: dist.zip
    on:
      tags: true
      branch: master
      repo: manzt/higlass-unix-time-track
  - provider: npm
    skip_cleanup: true
    email: trevmanz94@gmail.com
    api_key:
      secure: "clML9yQyI+o7Kk1dTjKHhJrRyYB2aVPX2qmSiuVhhtteDYF6mBEtS6NTfmZaVxuDsCVl8AamuraGt4rjEe/Sqn/GtlsdSqgqW5+9Yt6tHZh07eAQJzIjr9vKGcnXaWpvaSPlgcuM3uiLW9F8dNyFdyJ/52PO7Sjl8UqAh0VX3cb5KSHPXHYCQVrrsGld7QjfcbGu6KW6/fVJDngeQ3KD3fnntIgsY+HSSxgxwPrTZeQXN7Wpdv4YexODZ1CCh+LmVsMaY2sXQyZU4mHMN67eVvCF4WyONPKHmz/y7+/7tSdth1lsDxFM+zMQ0erGINSm9d5SXve7xljx99UeIuEUIoRTfGW75oUqQDLQdcEIv2gnBSWbpbWW1bYbmxtRPgpckSFWyrXIp5ECJ9lz8rQaRZVVBDuAHXcgsMuV2fmza0msdCKX4Gpfa4C8Mdo9PbgFJZhRMYsG0WoCNTjixn/ihYM1ESKIVUkRhSke0xJGYvF4RrClZitAVTxQYQNpfuyE0QHaVS9nugxvptgGdMOhOc9UfsUfd3pa7nbqMAb26aQBHzc+9SVp0ntWhbAlQ0qcfl4+jczgOVxUtbY3amVu0QhnR4vuUEDIi4D0H38+RJZ8uHEooH5y59CegZvG68mWKsu7IhZ4DOpC6wnAKHHJG6mTMH28SFCnfjXi3LNXjNs="
    on:
      branch: master
      tags: true
      repo: manzt/higlass-unix-time-track
