language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
        secure: d0v6K+t4zEj5/Q50jWIx8fDbeZUoxe5gzh1OZu32dRGpcxwEQapS1MVxy/vn47t7JtDEVh72ukfqCdI0liuhObvW0xUZnsm7Ib0Z7dWgAChIz3nh5Sj+bNVrmefNliMWUTNSVbzrMJiHqKkXGor1yzKVrIV1HrKPvsceOVrMAS/txz0uowsi6YCIwdwscJvTPtKPfHq/653oPfItG78XgbQ42Jh4h7snuZH8K2WyB/hc5jmL6sUGfYRk4qbYE5iuKNN4Ckfe0PKg/O+FauZIDwhGJUnME1LnN33mLPhUUJ+Z4zAdPxcwfBBo811qId/aa/5RLy9bG6Ur+yZFZUhakJPALX/GrWGxJs8K4Ll2wDXoAOsPwZ4AlSFAy726ew/NZL6PVa/SNbybUyxrHhEJOyxFADUyvsAlSds9uN5qMKoNgGOV2iuDFlOTdZpTSLiL1lLAjf4qFKvB/hdWeuMcQ49DL+ISEeRGUV8GgWrObbL2Ax1YeDZ0lZnQRQQeuGEIjVUQHOvQXY6dY/sEztcaLvQ3E5Lp7iFnzjhKGSRY8/QAMRwDSyMl6dBrOIiYI7LzMLak/hyRgm8WjCbQ4vNIlHYC9OCIJ5RtpckTmsiHKYQxy3Ov+ufTRjZVBMGgSUMR3x9YJZ4UKcwnPMd+v5VIvTcDTkW/gYb2vcyLUHD3Bc4=
    file: dist.zip
    on:
        tags: true
        branch: master
        repo: manzt/higlass-unix-time-track
  - provider: npm
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: o5MzH+mx2GATdK+o6CrHbcjKkyollM7ZlxWkC8UQCAEvkNfao65Z7iR61sHcPKGZDz2n2UOc9Llx2KIbxK0CBSYTRxu4QO4U7TRqu7XXbGyFoxeC+A70A7pVQgG9zdAVrIeIkrzdQdKhsLWb0RL6U+tVaQ0qVQNPxW+5W9ns7PEkygaHu2URQGq/RlDKvRZqJRHgtpdVgv/S/qWBUc6BCHPjbKx/JSBjPjc/U2shVcXcVuNpZsfDgs93BjlIYHDRYoflA7498bJHEBlvtzrPvyBBmWviPzmEWmbCC/CVnWzYKS3fzXN02Q7N9pMOw367/wySW3D99Z+Dqb5h8o96GHv63unJXv0xvtUonxEhsv+bhGbhmBt6diFtyPL0NVnnyrO60ptDhqyae3ZsKTSud4FG2o/5rY1uzxtr4xxDfH7b/OLKGPg94c2FPLa+3aNUBvRseHPYWhZ8qgyI/H3ApFlZyWPJMTxRK+tPNEywQ5gn5CgNBud3cnw8qHs+aoI6BFNGCB0StcsGsGlADtr+2hFn/jv+lnQucs7iMyaHQGyR9nz+VhReze6cfyuPua0VCK8HQ6nG+a5TmkeWyQfO7VevWQIiWNyLP8GoeHqOKD9DzRojedufEOZ5YUOjAru08cbG3s+zjrSpj06aNDihLrzO4n7fgm9YPScWMunVTrg=
    on:
      branch: master
      tags: true
      repo: manzt/higlass-unix-time-track
