language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: flHLoht9nbaLCAnkonT472wVjd3dH55ngv8yWaOI8XKJvWrqAb/AjMiVeCMZ74nqZTacJjYczQIz6lhwcRBM61lfrfJZT5P80gcKiuvlpS1fBc/8/rZA3Y82fOu1iX8gwWEaWzpD8wEqkUjcdpfWMXqWlFP+SUJojACTB1kdDdmPS7wY1R5l3pkj/L1aORytDM8oPWh9VZc7bIxwlOXAOvFOE8TgPXEafmKlYYy/9E6awVRByd/dYH6Ltaf1SiaS+3KU+D5UEu4Qf3FY2Ww/r6eHMK5UQVd7KtNFSTOcKLrNhFJUWa/yiBipo3JdSP8ab+AuOjdptJ/WqdvkPEQtOebQvlFgukjTkPWuec7ynDqiDaiInn7JJB8j19WIzOmF+qGtjBcugstwpA+/8eZIaQugMxAEHG6kTdU+iprc/YXHLynk/xUAQGWByG/AW7NDz8nKVsjl/3juP5y8kTOQ7DaZDOfGGKoStMaPz/4U9js9Wjug1zgEHxoNRUsUIwnguq1AZpjI9Vt0/judtJV2vbHJQrP3zeiY0EIIevzN2Q9/LCesY2uriT6Pi/quxlV1S6Fs+UAvWH9fbfn1yuM3WX7z11fKTdUUM+IlRh1chUN2BOkeUEs53c6iV6+JVcOH2APFstXRvFFYga0MsqvECxuoLrdXzTMIgpLg0tGb1Nw=
    file: dist.zip
    on:
      tags: true
      branch: master
      repo: manzt/higlass-unix-time-track
  - provider: npm
    email: trevmanz94@gmail.com
    api_key:
      secure: cyFBoYl2FnYCYudzJDuBMHJHUla9oA2wB3e/6DSChY1JFPEHdyiOmT0sEY/I8WsIKjdJDFe4IoWhriH84JobUo7syK1jaPCOgYuot67Ktn4gq0kpgohgJZ2QVUnc2G8FIy1goXtOP0TKS8M7/isaoCZPI26LVYgcQNsSY1zpoexoSp89qMx0BarGtiBjc71jRW2DVM2RxrZtxb/svQTx4clzV1MiZHpS6g6c+EwIx7rLF8uK7su/Mfs7sWHKepmHpQb0avOoUWMzjbFliaVo4o0DdMTxrbD11CG23JW77lGHrU9a0xVyjmjUdVd3WaKQ4H5bxs9eaMW8Vz/wvELL/exfAavPtyak9WJRuX/FdHmQaK2Zuhv5aw0IsWzawiO/aqVr8Y9cX32k/RtQJXSB775dhs/tkw4A5DbQLgGlU85M14+ltcesuidea5ZsBU/P1+KYFDlK3C7scx3ClbQHJgLrEyf+lx9aDcBipHj2K17RO3USDH8UDQDJ8W2LkUdc734exLghqKKUXN+XgWJwmHC6VK9vI8SzxMTw9+CnRvPgZd11QmVrRdhTS9gl3D5uzxfF2rRcnHY9opUaNuJq/xz5NwASFpFDexoLnyI+77Xe/LamNvPCFULi4akcDA+qwU5U3NWL5J2DZmPWDK9ol2G4XJtONhvhwUeeAhHq/Uo=
    on:
      branch: master
      tags: true
      repo: manzt/higlass-unix-time-track
