language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure:
        "RGkAqvcSFYStzgC6VvbphFtFYgmg5nQpn8sIv9iLh464Er8vU85XJREpRxP2/xG8CURcV6Bw6JwfelgINzwlpL+zCn+0ZhFVqYe1uSZ/p0+xURph9GxeliSjRCC9wbUW5fynU5QyTN3+65TXr01nktECtlFaQrlB3cP4C4+g7Sxp884bWADqfs8rn7/qNCsLh4fBg/JxjVt+FlOkUMSsV+5rKE776AtFXIUYK5FkcR7nmJOjhoBtrEmcjGkUJA7u1K/Y0gbeFdIpa0bsfqavxKBtQPzm7v9EXo1sGlyjN1pt2dZITJnw4Pjcmraz5FLzN6FDd17oCkzcZo7oqNvbMiOr5W7hZJv27AqxRK54Z6U1C6lRpWnI3QgecfbbQd7+9hXfPwtN5iKeff4ZKd7drWkCGxGrYpaknhLgj2f3vTRFAX6j38hZesOmotUmyWhb5Z2uYyOBuvK7Esa4mnsC9oPD1ZWECqiopy4Vz+pGLDsDBfpnbaZ0hAzKY6yCnHs3aSwxd7vxYVGgSycpo0WM6b/CZaunOe43lCWn3lqN40EcsvJuLTTm2ppjbh8cMYD7pRwsBbeHCgxUJDdPalNfBace83NCdYGAWyvEcXAkstoqvmBsjYmq0oIxLd2mdXiG95jgi+d78Txk0BDn0n6+4XtO42FH93FzXPkTB10F2mg="
    file: dist.zip
    on:
      tags: true
      branch: master
      repo: manzt/higlass-unix-time-track
  - provider: npm
    skip_cleanup: true
    email: trevmanz94@gmail.com
    api_key:
      secure: "clML9yQyI+o7Kk1dTjKHhJrRyYB2aVPX2qmSiuVhhtteDYF6mBEtS6NTfmZaVxuDsCVl8AamuraGt4rjEe/Sqn/GtlsdSqgqW5+9Yt6tHZh07eAQJzIjr9vKGcnXaWpvaSPlgcuM3uiLW9F8dNyFdyJ/52PO7Sjl8UqAh0VX3cb5KSHPXHYCQVrrsGld7QjfcbGu6KW6/fVJDngeQ3KD3fnntIgsY+HSSxgxwPrTZeQXN7Wpdv4YexODZ1CCh+LmVsMaY2sXQyZU4mHMN67eVvCF4WyONPKHmz/y7+/7tSdth1lsDxFM+zMQ0erGINSm9d5SXve7xljx99UeIuEUIoRTfGW75oUqQDLQdcEIv2gnBSWbpbWW1bYbmxtRPgpckSFWyrXIp5ECJ9lz8rQaRZVVBDuAHXcgsMuV2fmza0msdCKX4Gpfa4C8Mdo9PbgFJZhRMYsG0WoCNTjixn/ihYM1ESKIVUkRhSke0xJGYvF4RrClZitAVTxQYQNpfuyE0QHaVS9nugxvptgGdMOhOc9UfsUfd3pa7nbqMAb26aQBHzc+9SVp0ntWhbAlQ0qcfl4+jczgOVxUtbY3amVu0QhnR4vuUEDIi4D0H38+RJZ8uHEooH5y59CegZvG68mWKsu7IhZ4DOpC6wnAKHHJG6mTMH28SFCnfjXi3LNXjNs="
    on:
      branch: master
      tags: true
      repo: manzt/higlass-unix-time-track
